// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZw8yJZwr1nE0SeUqqqiY-44qWyBThvo',
    appId: '1:78402258292:web:ecfd26e56497786d211821',
    messagingSenderId: '78402258292',
    projectId: 'intelliview-fd426',
    authDomain: 'intelliview-fd426.firebaseapp.com',
    storageBucket: 'intelliview-fd426.firebasestorage.app',
    measurementId: 'G-XYSJYMHQZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzt50NeiZREP2L7kkKpNW84iuyvhgg-8',
    appId: '1:78402258292:android:5541a49a21d957ad211821',
    messagingSenderId: '78402258292',
    projectId: 'intelliview-fd426',
    storageBucket: 'intelliview-fd426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_MBlbDLPLl2bp8Axmc5PCb3Q2idvtKB4',
    appId: '1:78402258292:ios:e50819c8c2c2df7e211821',
    messagingSenderId: '78402258292',
    projectId: 'intelliview-fd426',
    storageBucket: 'intelliview-fd426.firebasestorage.app',
    iosBundleId: 'com.example.intelliview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_MBlbDLPLl2bp8Axmc5PCb3Q2idvtKB4',
    appId: '1:78402258292:ios:e50819c8c2c2df7e211821',
    messagingSenderId: '78402258292',
    projectId: 'intelliview-fd426',
    storageBucket: 'intelliview-fd426.firebasestorage.app',
    iosBundleId: 'com.example.intelliview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXZw8yJZwr1nE0SeUqqqiY-44qWyBThvo',
    appId: '1:78402258292:web:9ea448c5a8ba4e23211821',
    messagingSenderId: '78402258292',
    projectId: 'intelliview-fd426',
    authDomain: 'intelliview-fd426.firebaseapp.com',
    storageBucket: 'intelliview-fd426.firebasestorage.app',
    measurementId: 'G-Q1Z57JZKKY',
  );

}